<?php

// Plugin definition
$plugin = array(
  'title' => t('Australian Apprenticeships Home'),
  'category' => t('Australian Apprenticeships'),
  'icon' => 'home-layout.png',
  'theme' => 'home_layout',
  'css' => 'home-layout.css',
  'regions' => array(
    'top_left' => t('Top left'),
    'top_right' => t('Top right'),
    'bottom_left' => t('Bottom left'),
    'bottom_center' => t('Bottom center'),
    'bottom_right' => t('Bottom right'),
  ),
);
